import type { Metadata } from "next";
import { Lato } from "next/font/google";
import CookiePopUp from "./components/Cookie/CookiePopUp";
import Header from "./components/header";
import "./globals.css";
import { cn } from "./utils/cn";
import { Toaster } from "react-hot-toast";
const lato = Lato({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Bookjourney",
  description: "Generated by create next app",
};
import ReactQueryProvider from "./providers/ReactQueryProvider";
import { ThemeProvider } from "./providers/theme-provider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          <AppRouterCacheProvider>
            <ThemeProvider>
              <Toaster />
              {children}
              <CookiePopUp></CookiePopUp>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
