import type { Metadata } from "next";
import CookiePopUp from "./components/Cookie/CookiePopUp";
import "./globals.css";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Bookjourney",
  description: "Generated by create next app",
};
import ReactQueryProvider from "./providers/ReactQueryProvider";
import { ThemeProvider } from "./providers/theme-provider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          <AppRouterCacheProvider>
            <ThemeProvider>
              <Toaster />
              {children}
              <CookiePopUp></CookiePopUp>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
