import type { Metadata } from "next";
import { Lato } from "next/font/google";
import CookiePopUp from "./components/Cookie/CookiePopUp";
import Header from "./components/header";
import Modal from "./components/Modal/Modal";
import LogForm from "./components/SignInForm/LogForm";
import "./globals.css";

const lato = Lato({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Bookjourney",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg">
        <Header children={undefined} auth={undefined} />
        {children}
        <CookiePopUp></CookiePopUp>
      </body>
    </html>
  );
}
